openapi: 3.0.0
info:
  title: KU PLACE API
  description:
    TBA.
  version: 1.0.0
servers:
- url: /ku-place
paths:
  /locations/{locationId}:
    parameters:
    - name: locationId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Return a name of location with their specific latitude and lontitude.
      operationId: controller.get_building_detail
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildingFull'
  /securities/{securityId}:
    parameters:
      - name: securityId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a link of specifi security and provide their latitude and lontitude
      operationId: controller.get_security_image
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityImg'
  /securitylocation/{locationId}:
    parameters:
      - name: locationId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Provide the nearby light location and security location
      operationId: controller.get_security_location
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityLocation'
  /lightlocation/{locationId}:
    parameters:
      - name: locationId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Provide the latitude and lontitude of light location
      operationId: controller.get_light_location
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LightLocation'

  /pmlocation/{locationId}:
    parameters:
      - name: locationId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Provide the average pm
      operationId: controller.get_average_pm
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PMAverage'

components:
  schemas:
    StationShort:
      type: object
      properties:
        stationId:
          type: integer
        name:
          type: string
    TestFromMark:
      type: object
      properties:
        light:
          type: integer
    BuildingFull:
      type: object
      properties:
        building:
          type: string
        lat:
          type: number
        lon:
          type: number
          description: เดี๋ยวจอมมาใส่
    SecurityImg:
      type: object
      properties:
        img_link:
          type: string
        lat:
          type: number
        lon:
          type: number
    SecurityLocation:
      type: object
      properties:
        building:
          type: string
        security_id:
          type: integer
        img_link:
          type: string
        lat:
          type: number
        lon:
          type: number
        distance:
          type: number
    LightLocation:
      type: object
      properties:
        building:
          type: string
        sensor_lat:
          type: integer
        sensor_lon:
          type: integer
        time:
          type: string
        value_light:
          type: integer
    PMAverage:
      type: object
      properties:
        building:
          type: string
        lat:
          type: integer
        lon:
          type: integer
        time:
          type: string
        average_pm:
          type: integer


